# Generated by Django 5.1.1 on 2024-09-16 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_episode_image_alter_episode_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='comment',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.episode'),
        ),
    ]
